In [1]:
import pandas as pd
import numpy as np

## Creacion dataframes ##

In [2]:
customers=pd.read_csv('../raw/olist_customers_dataset.csv')
geolocation=pd.read_csv('../raw/olist_geolocation_dataset.csv')
order_items=pd.read_csv('../raw/olist_order_items_dataset.csv')
order_payments=pd.read_csv('../raw/olist_order_payments_dataset.csv')
order_reviews=pd.read_csv('../raw/olist_order_reviews_dataset.csv')
orders=pd.read_csv('../raw/olist_orders_dataset.csv')
products=pd.read_csv('../raw/olist_products_dataset.csv')
sellers=pd.read_csv('../raw/olist_sellers_dataset.csv')
product_category_translation=pd.read_csv('../raw/product_category_name_translation.csv')

## Conexiones: keys ##

| Tabla Origen | Tabla Destino | Key (Columna de unión) |
| :--- | :--- | :--- |
| `olist_orders_dataset` | `olist_order_payments_dataset` | `order_id` |
| `olist_orders_dataset` | `olist_order_reviews_dataset` | `order_id` |
| `olist_orders_dataset` | `olist_order_items_dataset` | `order_id` |
| `olist_orders_dataset` | `olist_customers_dataset` | `customer_id` |
| `olist_order_items_dataset` | `olist_products_dataset` | `product_id` |
| `olist_order_items_dataset` | `olist_sellers_dataset` | `seller_id` |
| `olist_sellers_dataset` | `olist_geolocation_dataset` | `zip_code_prefix` |
| `olist_order_customer_dataset` | `olist_geolocation_dataset` | `zip_code_prefix` |

## Cambios a realizar ## 

### Customers ### 
- DTypes ok   **Listo**
- No hay nulos  **Listo**
- No hay duplicados **Listo**
- Cambiar textos de customer_city a Title y eliminar espacios extra posibles (nova itapirema ---> Nova Itapirema) ---> optimizacion nombres para visualizacion en Power BI. **Listo**  
- Quitar posibles espacios en customer_state. **Listo**
  

### Geolocation ### 
-  Dtypes ok **Listo**
-  No hay nulos **Listo**
-  Hay duplicados. Eliminar al compartir la misma dirección que puede extraerse por el mismo zip_code.  **Listo** 
- Cambiar textos de customer_city a Title y eliminar espacios extra posibles (nova itapirema ---> Nova Itapirema) **Listo**  
- Quitar posibles espacios en customer_state **Listo**  
- Cambios de nombres de columnas para union de tablas por key: **Listo**  
    - Cambiar geolocation_city a Title y eliminar espacios extra posibles


### Order Items ###
- No hay nulos **Listo**
- No hay duplicados  **Listo**
- Cambiar shipping_limit_date a fecha. Formato: 2017-07-27 09:43:06 **Listo**
-  Precio: ojo, son reales brasileños (BRL): 1 real, 15 centimos. 50 reales, 7.64 euros aprox. Cambiar titulo columna a price_brl? Lo dejamos como está para mejor legibilidad en dashboard, cambio a formato moneda allí. **Listo**
- Cambios de nombres de columnas para union de tablas por key no necesarios: **Listo** 
    - order_id ok
    - product_id ok
    - seller_id ok
- Descargar en parquet para evitar eliminar fecha al guardar el dataframe limpio

### Order Payments ###  
- Dtype ok **Listo**
- No hay nulos **Listo**  
- No hay duplicados **Listo**  
- Cambiar texto columna payment type de barra baja a espacio (credit_card --> credit card) **Listo**  
- Cambios de nombres de columnas para union de tablas por key no necesarios:
    - order_id


### Order Reviews ###
- No hay duplicados  **Listo**  
- Hay nulos en review_comment_title y review_comment_message. Ver porcentaje del total para eliminación o no utilizacion de este dataframe, no pueden sustituirse por medias/medianas al ser textos. Muchos, dejamos como nulos. **Listo**  
- Cambiar columnas a fecha: **Listo**  
    - review_creation_date. Formato: 2018-08-23 00:00:00  
    - review_answer_timestamp. Formato: 2018-08-23 19:14:41  
- Cambios de nombres de columnas para union de tablas por key no necesarios:  **Listo** 
    - review_id  
    - order_id  
- Descargar en parquet para evitar eliminar fecha al guardar el dataframe limpio.  

### Orders ###
- No hay duplicados **Listo**  
- Hay nulos en order_approved_at, order_delivered_carrier_date y order_delivered_customer_date. Ver porcentaje del total para eliminación, no pueden sustituirse por medias/medianas al ser fechas. Se dejan, tiene sentido que no haya fechas al ser de pedidos no entregados (cancelados, en proceso, etc). **Listo**  
- Cambiar columnas a fecha: **Listo**  
    - order_purchase_timestamp. Formato: 2018-08-06 06:42:46	
    - order_approved_at. Formato: 2018-08-06 06:50:13	
    - order_delivered_carrier_date. Formato: 2018-08-07 07:38:00	
    - order_delivered_customer_date. Formato: 2018-08-16 19:25:28	
    - order_estimated_delivery_date. Formato: 2018-08-27 00:00:00
- Cambios de nombres de columnas para union de tablas por key no necesarios: **Listo** 
    - order_id
    - customer_id
- Descargar en parquet para evitar eliminar fecha al guardar el dataframe limpio.

### Products ###  
- Dtype ok.  **Listo**  
- No hay duplicados **Listo**  
- Cambiar textos de product_category_name a Title, eliminar espacios y eliminar espacios extra posibles. ---> optimizacion nombres para visualizacion en Power BI. **Listo** OJO: Tiene que coincidir como key a dataframe translation.  
- Hay nulos en casi todas las columnas. Ver porcentaje del total para eliminación. Eliminados los valores nulos al ser poco porcentaje  respecto al total (menos del 2%) **Listo**  
- Cambios de nombres de columnas para union de tablas por key no necesarios: **Listo** 
    - product_id
    - product_category_name 


### Sellers ###  
- Dtype ok **Listo**  
- No hay nulos  **Listo**  
- No hay duplicados **Listo**  
- Cambiar textos de seller_city a Title y eliminar espacios extra posibles (nova itapirema ---> Nova Itapirema) **Listo**  
- Quitar posibles espacios en seller_state **Listo**


### Category translation ### 
- Dtype ok. **Listo**  
- No hay nulos. **Listo**  
- No hay duplicados. **Listo**  
- Cambiar textos de product_category_name a Title, eliminar espacios y eliminar espacios extra posibles. **Listo**   OJO: Tiene que coincidir como key a dataframe products. 
- Cambiar textos de product_category_name_english a Title, eliminar espacios y eliminar espacios extra posibles. **Listo**

## Info dataset customers ##

In [3]:
customers.sample(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
21630,05e1dc39bf70b42e5110b787c846f88d,8858ebdc3765f9aeb72a495bb3b2328f,79083,campo grande,MS
64901,78783cd0f4085749b3c1b5eb9abc6d09,7ee397d3532b08254b5d9ef4e8c129a9,63250,milagres,CE
16267,3fb8d3153876e8ddc599b0897537310a,a1fac7857c6b883929b8de54fb33ae7a,97010,santa maria,RS
95008,2877d92a0925bf30fe19e44ef779e533,9d5a965adb4373036f892cd149e37395,37600,cambui,MG
59972,516a37d1245dd9d6c5bad03d4138dac8,5224f4a19e5f63ba725c130ee96ec602,11060,santos,SP

In [4]:
customers.shape

(99441, 5)

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [6]:
customers.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_zip_code_prefix,99441.0,35137.474583,29797.938996,1003.0,11347.0,24416.0,58900.0,99990.0

In [7]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [8]:
customers.duplicated().sum()

np.int64(0)

In [9]:
filas_duplicadas_customers = customers[customers.duplicated(keep=False)]
filas_duplicadas_customers

Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

## Info dataset geolocation ##

In [10]:
geolocation.sample(5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
412315,20541,-22.921456,-43.240880,rio de janeiro,RJ
769081,68148,-3.299379,-52.543154,brasil novo,PA
21,1020,-23.552235,-46.628441,são paulo,SP
440322,22051,-22.971660,-43.190496,rio de janeiro,RJ
146838,5844,-23.659642,-46.742183,sao paulo,SP

In [11]:
geolocation.shape

(1000163, 5)

In [12]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [13]:
geolocation.describe().T

,count,mean,std,min,25%,50%,75%,max
geolocation_zip_code_prefix,1000163.0,36574.166466,30549.335710,1001.000000,11075.000000,26530.000000,63504.000000,99990.000000
geolocation_lat,1000163.0,-21.176153,5.715866,-36.605374,-23.603546,-22.919377,-19.979620,45.065933
geolocation_lng,1000163.0,-46.390541,4.269748,-101.466766,-48.573172,-46.637879,-43.767709,121.105394

In [14]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [15]:
geolocation.duplicated().sum()

np.int64(261831)

In [16]:
filas_duplicadas_geolocation = geolocation[geolocation.duplicated(keep=False)]
filas_duplicadas_geolocation.head(15)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP
10,1013,-23.547325,-46.634184,sao paulo,SP
13,1012,-23.548946,-46.634671,sao paulo,SP
15,1046,-23.546081,-46.644820,sao paulo,SP
16,1039,-23.541883,-46.639919,sao paulo,SP
17,1024,-23.541390,-46.629899,são paulo,SP
18,1009,-23.546935,-46.636588,sao paulo,SP
19,1046,-23.545884,-46.643163,sao paulo,SP
20,1046,-23.545166,-46.643786,sao paulo,SP

## Info dataset order items ##

In [17]:
order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
96651,db5d80117e19d41e6bee8c7ef9615a20,1,c795f412e17c825c7765adfdb4ecdc56,f8db351d8c4c4c22c6835c19a46f01b0,2017-10-26 19:49:29,15.90,16.79
20480,2ef2818bc1477c39bc32b093812b85e8,1,d7423500e1911ba5972c229b2fb974ca,7299e27ed73d2ad986de7f7c77d919fa,2018-06-05 14:50:31,90.00,18.51
11412,19fb3160f1bdded8463061ab9385fbfc,1,00f179926ae5965cd6ff548d765d8a61,8b28d096634035667e8263d57ba3368c,2017-11-03 02:50:09,15.87,15.10
36794,5396a52ab4998b4d8ccb51b73cbc35d1,1,951b64df30a368d839ae1e534ff79bd9,edb58a1390adf273840030a3d6253829,2018-08-30 11:25:20,39.90,18.38
5695,0cd445b0eedab80706bb88ed32325d08,1,785365b9ad25d832bdde56f305159fdb,a3e9a2c700480d9bb01fba070ba80a0e,2017-07-12 22:10:13,56.00,17.64

In [18]:
order_items.shape

(112650, 7)

In [19]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [20]:
order_items.describe().T

,count,mean,std,min,25%,50%,75%,max
order_item_id,112650.0,1.197834,0.705124,1.00,1.00,1.00,1.00,21.00
price,112650.0,120.653739,183.633928,0.85,39.90,74.99,134.90,6735.00
freight_value,112650.0,19.990320,15.806405,0.00,13.08,16.26,21.15,409.68

In [21]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [22]:
order_items_duplicados=order_items.duplicated()
order_items_duplicados.sum()

np.int64(0)

In [23]:
order_items.duplicated().sum()

np.int64(0)

In [24]:
filas_duplicadas_order_items = order_items[order_items.duplicated(keep=False)]
filas_duplicadas_order_items

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

## Info dataset payments ##

In [25]:
order_payments.sample(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
40313,7258f5b1cf840900c133d9f7192b7a84,1,credit_card,2,203.52
78641,2f0f1657f49de673ff9c502c8fd8235f,1,credit_card,3,96.65
66265,f98376009c93a60a4d80496d4e294637,1,credit_card,8,292.92
95010,f625767e8c7655c497c96abfbc1d7771,1,credit_card,1,44.09
102572,98f7b0bbb8eebba6398ec18bf1a8cf12,1,credit_card,1,161.10

In [26]:
order_payments.shape

(103886, 5)

In [27]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [28]:
order_payments.describe().T

,count,mean,std,min,25%,50%,75%,max
payment_sequential,103886.0,1.092679,0.706584,1.0,1.00,1.0,1.0000,29.00
payment_installments,103886.0,2.853349,2.687051,0.0,1.00,1.0,4.0000,24.00
payment_value,103886.0,154.100380,217.494064,0.0,56.79,100.0,171.8375,13664.08

In [29]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [30]:
order_payments.duplicated().sum()

np.int64(0)

## Info dataset reviews ##

In [31]:
order_reviews.sample(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
87027,07b9766d6d633276c6fcf5e591c7fabd,30552396e65cfc4856e8520b7867414f,4,NaN,NaN,2017-11-08 00:00:00,2017-11-08 15:49:31
64575,b4c48992c6ebbaa44fbbbd261df95bae,5f67873cb4b18c98b9f2015eaae0a752,1,NaN,A luva veio muito grande e não é igual da foto...,2017-09-06 00:00:00,2017-09-07 00:26:42
11432,e9c320cf06da4e63a958afa86edd91bb,6509ed1f01a321d9ae4958d09ef2038e,5,NaN,NaN,2017-08-25 00:00:00,2017-08-26 01:22:14
28092,2b2af0586bf7ee9fa8c4666116b4cc43,7776efd9111e9fc4702936560e4b0a10,4,NaN,NaN,2017-05-18 00:00:00,2017-05-19 08:27:31
29978,4d39ae35238e4af367c65ad241592c02,30dfd9f2d61a37d83d75eaba39d110f6,5,NaN,NaN,2017-06-28 00:00:00,2017-06-29 00:42:28

In [32]:
order_reviews.shape

(99224, 7)

In [33]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [34]:
order_reviews.describe().T

                count      mean       std  min  25%  50%  75%  max
review_score  99224.0  4.086421  1.347579  1.0  4.0  5.0  5.0  5.0

In [35]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [36]:
order_reviews.duplicated().sum()

np.int64(0)

## Info dataset orders ##

In [37]:
orders.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
92531,b0a472e075b205f9598c0dfb2cf6ed97,19f49de4b64f3bce50c45d5d57124bc6,delivered,2017-12-08 15:31:36,2017-12-08 15:52:50,2017-12-12 18:36:56,2017-12-17 18:59:12,2018-01-03 00:00:00
71888,134ecc3a051e0aef2889ae1d42e79b87,958c7d63ed65a1a8b8323e253609d52f,delivered,2017-12-09 21:00:31,2017-12-12 03:38:22,2017-12-12 17:39:13,2017-12-22 21:33:11,2018-01-11 00:00:00
4643,f36cda6db10b2dddb208bf63a6ef8dfc,bb15c99f5519bbc27a55868e043216de,delivered,2018-06-03 08:39:18,2018-06-05 03:55:22,2018-06-05 15:33:00,2018-06-11 14:21:36,2018-07-16 00:00:00
71527,799be3792f7db4e84ead1a2eefccd1b2,74d841cb5ec776ad34ebc824ad9906ce,delivered,2017-03-07 23:21:25,2017-03-07 23:33:21,2017-03-08 12:05:19,2017-03-10 18:10:13,2017-03-24 00:00:00
18313,32a7f2fa7d1b798b72a117f24095efd4,aa86a2174dde0b98dce3fab52890ca9b,delivered,2017-02-07 16:04:21,2017-02-07 16:15:15,2017-02-08 13:03:38,2017-02-13 05:51:39,2017-03-09 00:00:00

In [38]:
orders.shape

(99441, 8)

In [39]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [40]:
orders.describe().T

,count,unique,top,freq
order_id,99441,99441,66dea50a8b16d9b4dee7af250b4be1a5,1
customer_id,99441,99441,edb027a75a1449115f6b43211ae02a24,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-08-02 12:05:26,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-08 19:36:48,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

In [41]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [42]:
orders.duplicated().sum()

np.int64(0)

## Info dataset products ##

In [43]:
products.sample(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
16349,99d2542c137ffd3cea8e2867d95546c4,construcao_ferramentas_ferramentas,54.0,444.0,2.0,1050.0,25.0,25.0,25.0
32181,4c72e6d081c8a1b5430351d015eb86ba,moveis_decoracao,48.0,183.0,4.0,2000.0,35.0,15.0,25.0
5756,bfc121a2f5d97868f3a02ae6c5b5f5a2,cama_mesa_banho,44.0,167.0,1.0,1850.0,47.0,7.0,35.0
15376,bf359473d58e90d8fc29bf8f3d282ea9,artes,37.0,606.0,1.0,350.0,28.0,4.0,22.0
19062,64f905cf518f84bfe0fbcc33bf6f0e9a,esporte_lazer,26.0,303.0,1.0,983.0,28.0,15.0,29.0

In [44]:
products.shape

(32951, 9)

In [45]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [46]:
products.describe().T

,count,mean,std,min,25%,50%,75%,max
product_name_lenght,32341.0,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

In [47]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [48]:
products.duplicated().sum()

np.int64(0)

## Info dataset sellers ##

In [49]:
sellers.sample(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2573,8f2ce03f928b567e3d56181ae20ae952,5141,pirituba,SP
1355,e9511df20ccd82658a30c37b7fb343af,17026,bauru,SP
1775,f3c38ab652836d21de61fb8314b69182,1206,sao paulo,SP
2517,2f09f7d37a97956d11cc1a7cadd5262b,14090,ribeirao preto,SP
1204,cfa5ab0e4d3fc212fd0b3410e7081c62,36500,uba,MG

In [50]:
sellers.shape

(3095, 4)

In [51]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [52]:
sellers.describe().T

,count,mean,std,min,25%,50%,75%,max
seller_zip_code_prefix,3095.0,32291.059451,32713.45383,1001.0,7093.5,14940.0,64552.5,99730.0

In [53]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [54]:
sellers.duplicated().sum()

np.int64(0)

## Info dataset category translation ##

In [55]:
product_category_translation.sample(5)

                product_category_name product_category_name_english
40                    casa_construcao             home_construction
70                 seguros_e_servicos         security_and_services
30                  moveis_escritorio              office_furniture
37          agro_industria_e_comercio    agro_industry_and_commerce
43  construcao_ferramentas_iluminacao     construction_tools_lights

In [56]:
product_category_translation.shape

(71, 2)

In [57]:
product_category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [58]:
product_category_translation.describe().T

                              count unique            top freq
product_category_name            71     71   beleza_saude    1
product_category_name_english    71     71  health_beauty    1

In [59]:
product_category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [60]:
product_category_translation.duplicated().sum()

np.int64(0)