In [1]:
import pandas as pd
import numpy as np

## Creacion dataframes ##

In [2]:
customers=pd.read_csv('../raw/olist_customers_dataset.csv')
geolocation=pd.read_csv('../raw/olist_geolocation_dataset.csv')
order_items=pd.read_csv('../raw/olist_order_items_dataset.csv')
order_payments=pd.read_csv('../raw/olist_order_payments_dataset.csv')
order_reviews=pd.read_csv('../raw/olist_order_reviews_dataset.csv')
orders=pd.read_csv('../raw/olist_orders_dataset.csv')
products=pd.read_csv('../raw/olist_products_dataset.csv')
sellers=pd.read_csv('../raw/olist_sellers_dataset.csv')
product_category_translation=pd.read_csv('../raw/product_category_name_translation.csv')

## Cambio formato a fechas ##

In [3]:
# Creamos funcion para aplicar el cambio de fecha a los distintos dataframes

def cambiar_a_fecha (df):
        columnas_fechas= df.filter(like='_at').columns.tolist() + df.filter(like='_timestamp').columns.tolist()+ df.filter(like='_date').columns.tolist()
        for columna in columnas_fechas:
            df[columna] =pd.to_datetime(df[columna], format='%Y-%m-%d %H:%M:%S',errors='coerce')
        return df

In [4]:
# Creamos funcion para aplicar el cambio de fecha a los distintos dataframes (sin format)

def cambiar_a_fecha (df):
        columnas_fechas= df.filter(like='_at').columns.tolist() + df.filter(like='_timestamp').columns.tolist()+ df.filter(like='_date').columns.tolist()
        for columna in columnas_fechas:
            df[columna] =pd.to_datetime(df[columna],errors='coerce')
        return df

Aplicamos la funcion a los distintos dataframes

In [5]:
order_items= cambiar_a_fecha(order_items)
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [6]:
orders= cambiar_a_fecha(orders)
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [7]:
order_reviews= cambiar_a_fecha(order_reviews)
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 5.3+ MB

## Cambio texto columnas a Title ##

In [8]:
def formatear_texto_title (df, columnas):
    for columna in columnas:
        if columna in df.columns:
            df[columna]=df[columna].str.strip().str.title()
    return df

In [9]:
#informamos  cuales son las que hay que modificar

texto_columnas_title= ['customer_city','geolocation_city', 'seller_city', 'product_category_name', 'product_category_name_english', 'payment_type']

In [10]:
customers=formatear_texto_title(customers, texto_columnas_title)
geolocation=formatear_texto_title(geolocation, texto_columnas_title)
products=formatear_texto_title(products, texto_columnas_title)
order_payments=formatear_texto_title(order_payments,texto_columnas_title)
sellers= formatear_texto_title(sellers, texto_columnas_title)
product_category_translation=formatear_texto_title(product_category_translation, texto_columnas_title)

Comprobamos que está ok mirando algunas tablas

In [11]:
customers.sample(2)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
24542,572b683cea71aeb651b0429d41d15009,41517b30c9379c6bef376702f93e8de8,21012,Rio De Janeiro,RJ
19606,de5d252d0ffeb5ded6a1bf99b6f7e443,1790b6f9e4cef7f6fe5dba7ab79b7004,88101,Sao Jose,SC

In [12]:
geolocation.sample(2)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
253041,11320,-23.965361,-46.381997,Sao Vicente,SP
404109,19914,-22.963089,-49.854501,Ourinhos,SP

In [13]:
products.sample(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
31738,70d581e7cfecc88d345ee9c197d1fbc8,Pet_Shop,56.0,199.0,1.0,700.0,16.0,20.0,11.0
3488,5b55f963a5c26f723ea1b5d7872557d3,Papelaria,20.0,98.0,1.0,300.0,25.0,20.0,20.0

In [14]:
product_category_translation.sample(2)

   product_category_name product_category_name_english
60            La_Cuisine                    La_Cuisine
8              Telefonia                     Telephony

### Quitamos barras bajas y sustituimos como espacios, eliminamos posibles espacios extra

In [15]:
def quitar_barras_bajas_y_espacios_extra(df, columnas):
    for columna in columnas:
        if columna in df.columns:
            df[columna]=df[columna].str.replace('_',' ',regex=False).str.strip()
    return df

In [16]:
texto_columnas_espacios= ['customer_state', 'seller_state', 'payment_type', 'product_category_name', 'product_category_name_english']

In [17]:
customers=quitar_barras_bajas_y_espacios_extra(customers, texto_columnas_espacios)
geolocation= quitar_barras_bajas_y_espacios_extra(geolocation, texto_columnas_espacios)
order_payments= quitar_barras_bajas_y_espacios_extra(order_payments, texto_columnas_espacios)
sellers= quitar_barras_bajas_y_espacios_extra(sellers, texto_columnas_espacios)
products=quitar_barras_bajas_y_espacios_extra(products,texto_columnas_espacios)
product_category_translation=quitar_barras_bajas_y_espacios_extra(product_category_translation, texto_columnas_espacios)

In [18]:
customers.sample(2)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
15597,6e142629fc0c8f867cdf17fa378ca709,b5f76c3201d925951a9a78bc0c2ec81e,13056,Campinas,SP
36301,42cd1ae38937085bc5fbf0bfada57af1,c4eb99d1b5513defdeb43b8b22dd3de1,5364,Sao Paulo,SP

In [19]:
geolocation.sample(2)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
46339,3112,-23.557109,-46.604542,Sao Paulo,SP
815205,76993,-13.108135,-60.550780,Colorado Do Oeste,RO

In [20]:
order_payments.sample(2)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
756,88c9df242e26c36482168acfc3d250dc,1,Credit Card,8,188.50
89402,9cd69a292cbec7756bbef4d854c773ca,1,Credit Card,1,8.81

In [21]:
sellers.sample(2)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2585,35b96509602ec4b7da831b5cd73ff2c2,93040,Sao Leopoldo,RS
1516,4e42581f08e8cfc7c090f930bac4552a,13660,Portoferreira,SP

In [22]:
products.sample(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
31929,af64ef75bb87ced49e08b2f278bd8bb8,Automotivo,60.0,624.0,3.0,8150.0,34.0,18.0,16.0
9993,436bc964ed67950b4956ce42cda4b350,Perfumaria,40.0,975.0,2.0,83.0,16.0,11.0,13.0

In [23]:
product_category_translation.sample(2)

     product_category_name product_category_name_english
58                 Bebidas                        Drinks
55  Fashion Roupa Feminina        Fashio Female Clothing

### Cambio titulos de algunas columnas para estandarizar entre dataframes

#### Geolocation

In [25]:
geolocation.sample(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
293837,13186,-22.88331,-47.204299,Hortolandia,SP

In [26]:
geolocation= geolocation.rename(columns={'geolocation_zip_code_prefix':'zip_code_prefix', 'geolocation_city':'city', 'geolocation_state':'state'})
geolocation.sample(2)

        zip_code_prefix  geolocation_lat  geolocation_lng      city state
913995            88495       -28.102380       -48.672727  Garopaba    SC
642554            38182       -19.595846       -46.927197     Araxa    MG

### Gestion nulos

#### Order Reviews

In [28]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [29]:
(order_reviews.isnull().sum()/ len(order_reviews))*100

review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

Al ser un porcentaje tan alto de nulos en apartados donde no puede calcularse, de este dataframe nos ceñiremos en usar solamente el review_score.  

Nulo util para análisis: de todas las puntuaciones de reviews, en un 88% se decide no dejar un titulo, y un 58% no deja ningun mensaje.

#### Orders

In [30]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [31]:
(orders.isnull().sum()/len(orders))*100

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [32]:
orders['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [33]:
orders['order_status'].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [34]:
# Vemos cuantos de estos estados no son entregados
pedidos_no_entregados = (orders['order_status'] != 'delivered').mean() * 100

print(pedidos_no_entregados)

2.9796562785973593

Los nulos de fecha se coresponden a pedidos que no se han entregado, al coincidir el porcentaje de order_delivered_customer_date con los pedidos con estado no entregado (alrededor de un 2,8%)

#### Products

In [35]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [36]:
(products.isnull().sum()/len(products))*100

product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

Al ser tan pocos en porcentaje, los eliminamos del dataframe

In [37]:
products.dropna(subset=['product_category_name'], inplace=True)

In [38]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              1
product_length_cm             1
product_height_cm             1
product_width_cm              1
dtype: int64

In [39]:
products.dropna(subset=['product_weight_g'], inplace=True)

In [40]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

### Duplicados

#### Geolocation

In [41]:
geolocation.duplicated().sum()

np.int64(261831)

In [42]:
filas_duplicadas_geolocation = geolocation[geolocation.duplicated(keep=False)]
filas_duplicadas_geolocation.head(15)

    zip_code_prefix  geolocation_lat  geolocation_lng       city state
0              1037       -23.545621       -46.639292  Sao Paulo    SP
1              1046       -23.546081       -46.644820  Sao Paulo    SP
2              1046       -23.546129       -46.642951  Sao Paulo    SP
6              1047       -23.546273       -46.641225  Sao Paulo    SP
7              1013       -23.546923       -46.634264  Sao Paulo    SP
8              1029       -23.543769       -46.634278  Sao Paulo    SP
9              1011       -23.547640       -46.636032  Sao Paulo    SP
10             1013       -23.547325       -46.634184  Sao Paulo    SP
13             1012       -23.548946       -46.634671  Sao Paulo    SP
15             1046       -23.546081       -46.644820  Sao Paulo    SP
16             1039       -23.541883       -46.639919  Sao Paulo    SP
17             1024       -23.541390       -46.629899  São Paulo    SP
18             1009       -23.546935       -46.636588  Sao Paulo    SP
19             1046       -23.545884       -46.643163  Sao Paulo    SP
20             1046       -23.545166       -46.643786  Sao Paulo    SP

In [43]:

geolocation.drop_duplicates(inplace=True)
geolocation.duplicated().sum()

np.int64(0)

In [44]:
geolocation.head(15)

    zip_code_prefix  geolocation_lat  geolocation_lng       city state
0              1037       -23.545621       -46.639292  Sao Paulo    SP
1              1046       -23.546081       -46.644820  Sao Paulo    SP
2              1046       -23.546129       -46.642951  Sao Paulo    SP
3              1041       -23.544392       -46.639499  Sao Paulo    SP
4              1035       -23.541578       -46.641607  Sao Paulo    SP
5              1012       -23.547762       -46.635361  São Paulo    SP
6              1047       -23.546273       -46.641225  Sao Paulo    SP
7              1013       -23.546923       -46.634264  Sao Paulo    SP
8              1029       -23.543769       -46.634278  Sao Paulo    SP
9              1011       -23.547640       -46.636032  Sao Paulo    SP
10             1013       -23.547325       -46.634184  Sao Paulo    SP
11             1032       -23.538418       -46.634778  Sao Paulo    SP
12             1014       -23.546435       -46.633830  Sao Paulo    SP
13             1012       -23.548946       -46.634671  Sao Paulo    SP
14             1037       -23.545187       -46.637855  São Paulo    SP

In [45]:
geolocation.shape

(738332, 5)

#### Exportacion dataframes limpios

In [46]:
customers.to_parquet('olist_customers.parquet')

In [47]:
geolocation.to_parquet('olist_geolocation.parquet')
order_items.to_parquet('olist_orders_items.parquet')
order_payments.to_parquet('olist_order_payments.parquet')
order_reviews.to_parquet('olist_order_reviews.parquet')
orders.to_parquet('olist_orders.parquet')
products.to_parquet('olist_products.parquet')
sellers.to_parquet('olist_sellers.parquet')
product_category_translation.to_parquet('product_category_translation.parquet')